In [41]:
import pandas as pd
import seaborn as sns
import numpy as np
import os.path
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.preprocessing import power_transform, MinMaxScaler, StandardScaler
from imblearn import under_sampling, over_sampling
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

linux_dir = '/home/satan/Projects/Dataset/HCI/home-credit-default-risk/'
win_dir = 'D:/Projects/Dataset/HCI/home-credit-default-risk/'

In [42]:
def kdeplot_me(df, columns, hue=None, figsize=(30, 15)):
    plt.figure(figsize=figsize)
    for col_name, index in zip(columns, range(len(columns))):
        plt.subplot( int(len(columns)/6)+1  , 6, index+1)
        if hue != None:
            sns.kdeplot(data=df, x=col_name, hue=hue, color='green', linewidth=3, fill=True)
        else:
            sns.kdeplot(data=df, x=col_name, color='green', linewidth=3, fill=True)
        plt.xlabel(col_name)
    plt.show()

def violinplot_me(df, columns, hue=None, figsize=(30, 15)):
    plt.figure(figsize=figsize)
    for col_name, index in zip(columns, range(len(columns))):
        plt.subplot( int(len(columns)/6)+1  , 6, index+1)
        if hue != None:
            sns.violinplot(data=df, x=col_name, hue=hue, color='green', linewidth=3, fill=True)
        else:
            sns.violinplot(data=df, x=col_name, color='green', linewidth=3, fill=True)
        plt.xlabel(col_name)
    plt.show()
    
def boxplot_me(df, columns, x, figsize=(30, 15)):
    plt.figure(figsize=figsize)
    for col_name, index in zip(columns, range(len(columns))):
        plt.subplot( int(len(columns)/6)+1  , 6, index+1)
        sns.boxplot(data=df, x=x, y=col_name)
        plt.xlabel(col_name)
    plt.show()
       
def log_transform(temp_df, log_columns):
    for col in log_columns:
        if temp_df[col].min() == 0:
            # df[col] = np.log(df[col]+1)
            temp_df[col], fitted_lambda = stats.boxcox( ( temp_df[col] + 1) )
        elif df[col].min() > 0:
            # df[col] = np.log(df[col])
            temp_df[col], fitted_lambda = stats.boxcox( temp_df[col] )

def get_minmax_scaler(temp_df, columns):
    scaler = {}
    for col in columns:
        scaler[col] = MinMaxScaler().fit( np.array(temp_df[col]).reshape(-1,1) )
    return scaler

def get_standard_scaler(temp_df, columns):
    scaler = {}
    for col in columns:
        scaler[col] = StandardScaler().fit( np.array(temp_df[col]).reshape(-1,1) )
    return scaler

def apply_transform(scaler, temp_df):
    tmp_df = temp_df.copy()
    for col in scaler.keys():
        tmp_df[col] = scaler[col].transform( np.array(temp_df[col]).reshape(-1,1) )
    return tmp_df

In [45]:
try :
    app_train = pd.read_csv(linux_dir+'application_train.csv')
    # app_test = pd.read_csv(linux_dir+'application_test.csv')
except:
    app_train = pd.read_csv(win_dir+'application_train.csv')
    # app_test = pd.read_csv(win_dir+'application_test.csv')
app_train.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    SK_ID_CURR                    307511 non-null  int64
 1    TARGET                        307511 non-null  int64
 2    NAME_CONTRACT_TYPE            307511 non-null  object
 3    CODE_GENDER                   307511 non-null  object
 4    FLAG_OWN_CAR                  307511 non-null  object
 5    FLAG_OWN_REALTY               307511 non-null  object
 6    CNT_CHILDREN                  307511 non-null  int64
 7    AMT_INCOME_TOTAL              307511 non-null  float64
 8    AMT_CREDIT                    307511 non-null  float64
 9    AMT_ANNUITY                   307499 non-null  float64
 10   AMT_GOODS_PRICE               307233 non-null  float64
 11   NAME_TYPE_SUITE               306219 non-null  object
 12   NAME_INCOME_TYPE              307511 non-null  object
 13   NAME_EDUCATION_TYPE           307511 non-null  object
 14   NAME_FAMILY_STATUS            307511 non-null  object
 15   NAME_HOUSING_TYPE             307511 non-null  object
 16   REGION_POPULATION_RELATIVE    307511 non-null  float64
 17   DAYS_BIRTH                    307511 non-null  int64
 18   DAYS_EMPLOYED                 307511 non-null  int64
 19   DAYS_REGISTRATION             307511 non-null  float64
 20   DAYS_ID_PUBLISH               307511 non-null  int64
 21   OWN_CAR_AGE                   104582 non-null  float64
 22   FLAG_MOBIL                    307511 non-null  int64
 23   FLAG_EMP_PHONE                307511 non-null  int64
 24   FLAG_WORK_PHONE               307511 non-null  int64
 25   FLAG_CONT_MOBILE              307511 non-null  int64
 26   FLAG_PHONE                    307511 non-null  int64
 27   FLAG_EMAIL                    307511 non-null  int64
 28   OCCUPATION_TYPE               211120 non-null  object
 29   CNT_FAM_MEMBERS               307509 non-null  float64
 30   REGION_RATING_CLIENT          307511 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    307511 non-null  object
 33   HOUR_APPR_PROCESS_START       307511 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    307511 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    307511 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   307511 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        307511 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        307511 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       307511 non-null  int64
 40   ORGANIZATION_TYPE             307511 non-null  object
 41   EXT_SOURCE_1                  134133 non-null  float64
 42   EXT_SOURCE_2                  306851 non-null  float64
 43   EXT_SOURCE_3                  246546 non-null  float64
 44   APARTMENTS_AVG                151450 non-null  float64
 45   BASEMENTAREA_AVG              127568 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 47   YEARS_BUILD_AVG               103023 non-null  float64
 48   COMMONAREA_AVG                92646 non-null   float64
 49   ELEVATORS_AVG                 143620 non-null  float64
 50   ENTRANCES_AVG                 152683 non-null  float64
 51   FLOORSMAX_AVG                 154491 non-null  float64
 52   FLOORSMIN_AVG                 98869 non-null   float64
 53   LANDAREA_AVG                  124921 non-null  float64
 54   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 55   LIVINGAREA_AVG                153161 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 57   NONLIVINGAREA_AVG             137829 non-null  float64
 58   APARTMENTS_MODE               151450 non-null  float64
 59   BASEMENTAREA_MODE             127568 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 61   YEARS_BUILD_MODE              103023 non-null  float64
 62   COMMONAREA_MODE               92646 non-null   float64
 63   ELEVATORS_MODE                143620 non-null  float64
 64   ENTRANCES_MODE                152683 non-null  float64
 65   FLOORSMAX_MODE                154491 non-null  float64
 66   FLOORSMIN_MODE                98869 non-null   float64
 67   LANDAREA_MODE                 124921 non-null  float64
 68   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 69   LIVINGAREA_MODE               153161 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 71   NONLIVINGAREA_MODE            137829 non-null  float64
 72   APARTMENTS_MEDI               151450 non-null  float64
 73   BASEMENTAREA_MEDI             127568 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 75   YEARS_BUILD_MEDI              103023 non-null  float64
 76   COMMONAREA_MEDI               92646 non-null   float64
 77   ELEVATORS_MEDI                143620 non-null  float64
 78   ENTRANCES_MEDI                152683 non-null  float64
 79   FLOORSMAX_MEDI                154491 non-null  float64
 80   FLOORSMIN_MEDI                98869 non-null   float64
 81   LANDAREA_MEDI                 124921 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 83   LIVINGAREA_MEDI               153161 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 85   NONLIVINGAREA_MEDI            137829 non-null  float64
 86   FONDKAPREMONT_MODE            97216 non-null   object
 87   HOUSETYPE_MODE                153214 non-null  object
 88   TOTALAREA_MODE                159080 non-null  float64
 89   WALLSMATERIAL_MODE            151170 non-null  object
 90   EMERGENCYSTATE_MODE           161756 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 96   FLAG_DOCUMENT_2               307511 non-null  int64
 97   FLAG_DOCUMENT_3               307511 non-null  int64
 98   FLAG_DOCUMENT_4               307511 non-null  int64
 99   FLAG_DOCUMENT_5               307511 non-null  int64
 100  FLAG_DOCUMENT_6               307511 non-null  int64
 101  FLAG_DOCUMENT_7               307511 non-null  int64
 102  FLAG_DOCUMENT_8               307511 non-null  int64
 103  FLAG_DOCUMENT_9               307511 non-null  int64
 104  FLAG_DOCUMENT_10              307511 non-null  int64
 105  FLAG_DOCUMENT_11              307511 non-null  int64
 106  FLAG_DOCUMENT_12              307511 non-null  int64
 107  FLAG_DOCUMENT_13              307511 non-null  int64
 108  FLAG_DOCUMENT_14              307511 non-null  int64
 109  FLAG_DOCUMENT_15              307511 non-null  int64
 110  FLAG_DOCUMENT_16              307511 non-null  int64
 111  FLAG_DOCUMENT_17              307511 non-null  int64
 112  FLAG_DOCUMENT_18              307511 non-null  int64
 113  FLAG_DOCUMENT_19              307511 non-null  int64
 114  FLAG_DOCUMENT_20              307511 non-null  int64
 115  FLAG_DOCUMENT_21              307511 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [38]:
app_cat_var = app_train.columns[app_train.dtypes == 'object'].tolist()
for col in app_cat_var:
    print(col,'\n',app_train[col].value_counts(),'\n')

NAME_CONTRACT_TYPE
 Cash loans         278232
Revolving loans     29279
Name: NAME_CONTRACT_TYPE, dtype: int64

CODE_GENDER
 F      202448
M      105059
XNA         4
Name: CODE_GENDER, dtype: int64

FLAG_OWN_CAR
 N    202924
Y    104587
Name: FLAG_OWN_CAR, dtype: int64

FLAG_OWN_REALTY
 Y    213312
N     94199
Name: FLAG_OWN_REALTY, dtype: int64

NAME_TYPE_SUITE
 Unaccompanied      248526
Family              40149
Spouse, partner     11370
Children             3267
Other_B              1770
Other_A               866
Group of people       271
Name: NAME_TYPE_SUITE, dtype: int64

NAME_INCOME_TYPE
 Working                 158774
Commercial associate     71617
Pensioner                55362
State servant            21703
Unemployed                  22
Student                     18
Businessman                 10
Maternity leave              5
Name: NAME_INCOME_TYPE, dtype: int64

NAME_EDUCATION_TYPE
 Secondary / secondary special    218391
Higher education                  74863
Incomplete higher                 10277
Lower secondary                    3816
Academic degree                     164
Name: NAME_EDUCATION_TYPE, dtype: int64

NAME_FAMILY_STATUS
 Married                 196432
Single / not married     45444
Civil marriage           29775
Separated                19770
Widow                    16088
Unknown                      2
Name: NAME_FAMILY_STATUS, dtype: int64

NAME_HOUSING_TYPE
 House / apartment      272868
With parents            14840
Municipal apartment     11183
Rented apartment         4881
Office apartment         2617
Co-op apartment          1122
Name: NAME_HOUSING_TYPE, dtype: int64

OCCUPATION_TYPE
 Laborers                 55186
Sales staff              32102
Core staff               27570
Managers                 21371
Drivers                  18603
High skill tech staff    11380
Accountants               9813
Medicine staff            8537
Security staff            6721
Cooking staff             5946
Cleaning staff            4653
Private service staff     2652
Low-skill Laborers        2093
Waiters/barmen staff      1348
Secretaries               1305
Realty agents              751
HR staff                   563
IT staff                   526
Name: OCCUPATION_TYPE, dtype: int64

WEEKDAY_APPR_PROCESS_START
 TUESDAY      53901
WEDNESDAY    51934
MONDAY       50714
THURSDAY     50591
FRIDAY       50338
SATURDAY     33852
SUNDAY       16181
Name: WEEKDAY_APPR_PROCESS_START, dtype: int64

ORGANIZATION_TYPE
 Business Entity Type 3    67992
XNA                       55374
Self-employed             38412
Other                     16683
Medicine                  11193
Business Entity Type 2    10553
Government                10404
School                     8893
Trade: type 7              7831
Kindergarten               6880
Construction               6721
Business Entity Type 1     5984
Transport: type 4          5398
Trade: type 3              3492
Industry: type 9           3368
Industry: type 3           3278
Security                   3247
Housing                    2958
Industry: type 11          2704
Military                   2634
Bank                       2507
Agriculture                2454
Police                     2341
Transport: type 2          2204
Postal                     2157
Security Ministries        1974
Trade: type 2              1900
Restaurant                 1811
Services                   1575
University                 1327
Industry: type 7           1307
Transport: type 3          1187
Industry: type 1           1039
Hotel                       966
Electricity                 950
Industry: type 4            877
Trade: type 6               631
Industry: type 5            599
Insurance                   597
Telecom                     577
Emergency                   560
Industry: type 2            458
Advertising                 429
Realtor                     396
Culture                     379
Industry: type 12           369
Trade: type 1               348
Mobile                      317
Legal Services              305
Cleaning                    260
Transport: type 1           201
Industry: type 6            112
Industry: type 10           109
Religion                     85
Industry: type 13            67
Trade: type 4                64
Trade: type 5                49
Industry: type 8             24
Name: ORGANIZATION_TYPE, dtype: int64

FONDKAPREMONT_MODE
 reg oper account         73830
reg oper spec account    12080
not specified             5687
org spec account          5619
Name: FONDKAPREMONT_MODE, dtype: int64

HOUSETYPE_MODE
 block of flats      150503
specific housing      1499
terraced house        1212
Name: HOUSETYPE_MODE, dtype: int64

WALLSMATERIAL_MODE
 Panel           66040
Stone, brick    64815
Block            9253
Wooden           5362
Mixed            2296
Monolithic       1779
Others           1625
Name: WALLSMATERIAL_MODE, dtype: int64

EMERGENCYSTATE_MODE
 No     159428
Yes      2328
Name: EMERGENCYSTATE_MODE, dtype: int64

In [72]:
temp_df = app_train.copy()

temp_df.OWN_CAR_AGE.fillna(0, inplace=True)
temp_df.loc[ temp_df.FLAG_OWN_CAR == 'N', 'OWN_CAR_AGE' ] = -1

temp_df.drop(index=temp_df[(temp_df.NAME_FAMILY_STATUS=='Unknown')|(temp_df.CODE_GENDER=='XNA')|(temp_df.NAME_INCOME_TYPE=='Maternity leave')].index, inplace=True)

# for index, values in temp_df.dtypes.items():
#     if values == 'object':
#         temp_df[index] = temp_df[index].fillna(temp_df[index].mode())
#     else:
#         temp_df[index] = temp_df[index].fillna(temp_df[index].median())

app_cat_binary = ['NAME_CONTRACT_TYPE','CODE_GENDER','FLAG_OWN_REALTY','FLAG_OWN_CAR','EMERGENCYSTATE_MODE']
app_cat_multi = [col for col in app_cat_var if col not in app_cat_binary + ['NAME_EDUCATION_TYPE']]
# app_cat_multi = [col for col in app_cat_var if col not in app_cat_binary + ['NAME_EDUCATION_TYPE','WEEKDAY_APPR_PROCESS_START']]
edu_map = {'Lower secondary':0, 'Secondary / secondary special': 1, 'Incomplete higher':2, 'Higher education':3, 'Academic degree':4}
days_map = {'MONDAY':0, 'TUESDAY': 1, 'WEDNESDAY':2, 'THURSDAY':3, 'FRIDAY':4, 'SATURDAY':5, 'SUNDAY':6}


for col in app_cat_binary:
    temp_dict = dict([ [i,j] for i,j in zip(temp_df[col].value_counts().index.to_list(),[0,1])])
    temp_df[col] = temp_df[col].map(temp_dict)
    
temp_df['NAME_EDUCATION_TYPE'] = temp_df['NAME_EDUCATION_TYPE'].map(edu_map) 

temp_df = pd.get_dummies(temp_df, columns=app_cat_multi, drop_first=True)

temp_df.replace([np.inf, -np.inf], np.nan, inplace=True)
temp_df.dropna(axis=0,inplace=True)
temp_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31232 entries, 0 to 307482
Data columns (total 224 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    SK_ID_CURR                                31232 non-null  int64
 1    TARGET                                    31232 non-null  int64
 2    NAME_CONTRACT_TYPE                        31232 non-null  int64
 3    CODE_GENDER                               31232 non-null  int64
 4    FLAG_OWN_CAR                              31232 non-null  int64
 5    FLAG_OWN_REALTY                           31232 non-null  int64
 6    CNT_CHILDREN                              31232 non-null  int64
 7    AMT_INCOME_TOTAL                          31232 non-null  float64
 8    AMT_CREDIT                                31232 non-null  float64
 9    AMT_ANNUITY                               31232 non-null  float64
 10   AMT_GOODS_PRICE                           31232 non-null  float64
 11   NAME_EDUCATION_TYPE                       31232 non-null  int64
 12   REGION_POPULATION_RELATIVE                31232 non-null  float64
 13   DAYS_BIRTH                                31232 non-null  int64
 14   DAYS_EMPLOYED                             31232 non-null  int64
 15   DAYS_REGISTRATION                         31232 non-null  float64
 16   DAYS_ID_PUBLISH                           31232 non-null  int64
 17   OWN_CAR_AGE                               31232 non-null  float64
 18   FLAG_MOBIL                                31232 non-null  int64
 19   FLAG_EMP_PHONE                            31232 non-null  int64
 20   FLAG_WORK_PHONE                           31232 non-null  int64
 21   FLAG_CONT_MOBILE                          31232 non-null  int64
 22   FLAG_PHONE                                31232 non-null  int64
 23   FLAG_EMAIL                                31232 non-null  int64
 24   CNT_FAM_MEMBERS                           31232 non-null  float64
 25   REGION_RATING_CLIENT                      31232 non-null  int64
 26   REGION_RATING_CLIENT_W_CITY               31232 non-null  int64
 27   HOUR_APPR_PROCESS_START                   31232 non-null  int64
 28   REG_REGION_NOT_LIVE_REGION                31232 non-null  int64
 29   REG_REGION_NOT_WORK_REGION                31232 non-null  int64
 30   LIVE_REGION_NOT_WORK_REGION               31232 non-null  int64
 31   REG_CITY_NOT_LIVE_CITY                    31232 non-null  int64
 32   REG_CITY_NOT_WORK_CITY                    31232 non-null  int64
 33   LIVE_CITY_NOT_WORK_CITY                   31232 non-null  int64
 34   EXT_SOURCE_1                              31232 non-null  float64
 35   EXT_SOURCE_2                              31232 non-null  float64
 36   EXT_SOURCE_3                              31232 non-null  float64
 37   APARTMENTS_AVG                            31232 non-null  float64
 38   BASEMENTAREA_AVG                          31232 non-null  float64
 39   YEARS_BEGINEXPLUATATION_AVG               31232 non-null  float64
 40   YEARS_BUILD_AVG                           31232 non-null  float64
 41   COMMONAREA_AVG                            31232 non-null  float64
 42   ELEVATORS_AVG                             31232 non-null  float64
 43   ENTRANCES_AVG                             31232 non-null  float64
 44   FLOORSMAX_AVG                             31232 non-null  float64
 45   FLOORSMIN_AVG                             31232 non-null  float64
 46   LANDAREA_AVG                              31232 non-null  float64
 47   LIVINGAPARTMENTS_AVG                      31232 non-null  float64
 48   LIVINGAREA_AVG                            31232 non-null  float64
 49   NONLIVINGAPARTMENTS_AVG                   31232 non-null  float64
 50   NONLIVINGAREA_AVG                         31232 non-null  float64
 51   APARTMENTS_MODE                           31232 non-null  float64
 52   BASEMENTAREA_MODE                         31232 non-null  float64
 53   YEARS_BEGINEXPLUATATION_MODE              31232 non-null  float64
 54   YEARS_BUILD_MODE                          31232 non-null  float64
 55   COMMONAREA_MODE                           31232 non-null  float64
 56   ELEVATORS_MODE                            31232 non-null  float64
 57   ENTRANCES_MODE                            31232 non-null  float64
 58   FLOORSMAX_MODE                            31232 non-null  float64
 59   FLOORSMIN_MODE                            31232 non-null  float64
 60   LANDAREA_MODE                             31232 non-null  float64
 61   LIVINGAPARTMENTS_MODE                     31232 non-null  float64
 62   LIVINGAREA_MODE                           31232 non-null  float64
 63   NONLIVINGAPARTMENTS_MODE                  31232 non-null  float64
 64   NONLIVINGAREA_MODE                        31232 non-null  float64
 65   APARTMENTS_MEDI                           31232 non-null  float64
 66   BASEMENTAREA_MEDI                         31232 non-null  float64
 67   YEARS_BEGINEXPLUATATION_MEDI              31232 non-null  float64
 68   YEARS_BUILD_MEDI                          31232 non-null  float64
 69   COMMONAREA_MEDI                           31232 non-null  float64
 70   ELEVATORS_MEDI                            31232 non-null  float64
 71   ENTRANCES_MEDI                            31232 non-null  float64
 72   FLOORSMAX_MEDI                            31232 non-null  float64
 73   FLOORSMIN_MEDI                            31232 non-null  float64
 74   LANDAREA_MEDI                             31232 non-null  float64
 75   LIVINGAPARTMENTS_MEDI                     31232 non-null  float64
 76   LIVINGAREA_MEDI                           31232 non-null  float64
 77   NONLIVINGAPARTMENTS_MEDI                  31232 non-null  float64
 78   NONLIVINGAREA_MEDI                        31232 non-null  float64
 79   TOTALAREA_MODE                            31232 non-null  float64
 80   EMERGENCYSTATE_MODE                       31232 non-null  float64
 81   OBS_30_CNT_SOCIAL_CIRCLE                  31232 non-null  float64
 82   DEF_30_CNT_SOCIAL_CIRCLE                  31232 non-null  float64
 83   OBS_60_CNT_SOCIAL_CIRCLE                  31232 non-null  float64
 84   DEF_60_CNT_SOCIAL_CIRCLE                  31232 non-null  float64
 85   DAYS_LAST_PHONE_CHANGE                    31232 non-null  float64
 86   FLAG_DOCUMENT_2                           31232 non-null  int64
 87   FLAG_DOCUMENT_3                           31232 non-null  int64
 88   FLAG_DOCUMENT_4                           31232 non-null  int64
 89   FLAG_DOCUMENT_5                           31232 non-null  int64
 90   FLAG_DOCUMENT_6                           31232 non-null  int64
 91   FLAG_DOCUMENT_7                           31232 non-null  int64
 92   FLAG_DOCUMENT_8                           31232 non-null  int64
 93   FLAG_DOCUMENT_9                           31232 non-null  int64
 94   FLAG_DOCUMENT_10                          31232 non-null  int64
 95   FLAG_DOCUMENT_11                          31232 non-null  int64
 96   FLAG_DOCUMENT_12                          31232 non-null  int64
 97   FLAG_DOCUMENT_13                          31232 non-null  int64
 98   FLAG_DOCUMENT_14                          31232 non-null  int64
 99   FLAG_DOCUMENT_15                          31232 non-null  int64
 100  FLAG_DOCUMENT_16                          31232 non-null  int64
 101  FLAG_DOCUMENT_17                          31232 non-null  int64
 102  FLAG_DOCUMENT_18                          31232 non-null  int64
 103  FLAG_DOCUMENT_19                          31232 non-null  int64
 104  FLAG_DOCUMENT_20                          31232 non-null  int64
 105  FLAG_DOCUMENT_21                          31232 non-null  int64
 106  AMT_REQ_CREDIT_BUREAU_HOUR                31232 non-null  float64
 107  AMT_REQ_CREDIT_BUREAU_DAY                 31232 non-null  float64
 108  AMT_REQ_CREDIT_BUREAU_WEEK                31232 non-null  float64
 109  AMT_REQ_CREDIT_BUREAU_MON                 31232 non-null  float64
 110  AMT_REQ_CREDIT_BUREAU_QRT                 31232 non-null  float64
 111  AMT_REQ_CREDIT_BUREAU_YEAR                31232 non-null  float64
 112  NAME_TYPE_SUITE_Family                    31232 non-null  uint8
 113  NAME_TYPE_SUITE_Group of people           31232 non-null  uint8
 114  NAME_TYPE_SUITE_Other_A                   31232 non-null  uint8
 115  NAME_TYPE_SUITE_Other_B                   31232 non-null  uint8
 116  NAME_TYPE_SUITE_Spouse, partner           31232 non-null  uint8
 117  NAME_TYPE_SUITE_Unaccompanied             31232 non-null  uint8
 118  NAME_INCOME_TYPE_Commercial associate     31232 non-null  uint8
 119  NAME_INCOME_TYPE_Pensioner                31232 non-null  uint8
 120  NAME_INCOME_TYPE_State servant            31232 non-null  uint8
 121  NAME_INCOME_TYPE_Student                  31232 non-null  uint8
 122  NAME_INCOME_TYPE_Unemployed               31232 non-null  uint8
 123  NAME_INCOME_TYPE_Working                  31232 non-null  uint8
 124  NAME_FAMILY_STATUS_Married                31232 non-null  uint8
 125  NAME_FAMILY_STATUS_Separated              31232 non-null  uint8
 126  NAME_FAMILY_STATUS_Single / not married   31232 non-null  uint8
 127  NAME_FAMILY_STATUS_Widow                  31232 non-null  uint8
 128  NAME_HOUSING_TYPE_House / apartment       31232 non-null  uint8
 129  NAME_HOUSING_TYPE_Municipal apartment     31232 non-null  uint8
 130  NAME_HOUSING_TYPE_Office apartment        31232 non-null  uint8
 131  NAME_HOUSING_TYPE_Rented apartment        31232 non-null  uint8
 132  NAME_HOUSING_TYPE_With parents            31232 non-null  uint8
 133  OCCUPATION_TYPE_Cleaning staff            31232 non-null  uint8
 134  OCCUPATION_TYPE_Cooking staff             31232 non-null  uint8
 135  OCCUPATION_TYPE_Core staff                31232 non-null  uint8
 136  OCCUPATION_TYPE_Drivers                   31232 non-null  uint8
 137  OCCUPATION_TYPE_HR staff                  31232 non-null  uint8
 138  OCCUPATION_TYPE_High skill tech staff     31232 non-null  uint8
 139  OCCUPATION_TYPE_IT staff                  31232 non-null  uint8
 140  OCCUPATION_TYPE_Laborers                  31232 non-null  uint8
 141  OCCUPATION_TYPE_Low-skill Laborers        31232 non-null  uint8
 142  OCCUPATION_TYPE_Managers                  31232 non-null  uint8
 143  OCCUPATION_TYPE_Medicine staff            31232 non-null  uint8
 144  OCCUPATION_TYPE_Private service staff     31232 non-null  uint8
 145  OCCUPATION_TYPE_Realty agents             31232 non-null  uint8
 146  OCCUPATION_TYPE_Sales staff               31232 non-null  uint8
 147  OCCUPATION_TYPE_Secretaries               31232 non-null  uint8
 148  OCCUPATION_TYPE_Security staff            31232 non-null  uint8
 149  OCCUPATION_TYPE_Waiters/barmen staff      31232 non-null  uint8
 150  WEEKDAY_APPR_PROCESS_START_MONDAY         31232 non-null  uint8
 151  WEEKDAY_APPR_PROCESS_START_SATURDAY       31232 non-null  uint8
 152  WEEKDAY_APPR_PROCESS_START_SUNDAY         31232 non-null  uint8
 153  WEEKDAY_APPR_PROCESS_START_THURSDAY       31232 non-null  uint8
 154  WEEKDAY_APPR_PROCESS_START_TUESDAY        31232 non-null  uint8
 155  WEEKDAY_APPR_PROCESS_START_WEDNESDAY      31232 non-null  uint8
 156  ORGANIZATION_TYPE_Agriculture             31232 non-null  uint8
 157  ORGANIZATION_TYPE_Bank                    31232 non-null  uint8
 158  ORGANIZATION_TYPE_Business Entity Type 1  31232 non-null  uint8
 159  ORGANIZATION_TYPE_Business Entity Type 2  31232 non-null  uint8
 160  ORGANIZATION_TYPE_Business Entity Type 3  31232 non-null  uint8
 161  ORGANIZATION_TYPE_Cleaning                31232 non-null  uint8
 162  ORGANIZATION_TYPE_Construction            31232 non-null  uint8
 163  ORGANIZATION_TYPE_Culture                 31232 non-null  uint8
 164  ORGANIZATION_TYPE_Electricity             31232 non-null  uint8
 165  ORGANIZATION_TYPE_Emergency               31232 non-null  uint8
 166  ORGANIZATION_TYPE_Government              31232 non-null  uint8
 167  ORGANIZATION_TYPE_Hotel                   31232 non-null  uint8
 168  ORGANIZATION_TYPE_Housing                 31232 non-null  uint8
 169  ORGANIZATION_TYPE_Industry: type 1        31232 non-null  uint8
 170  ORGANIZATION_TYPE_Industry: type 10       31232 non-null  uint8
 171  ORGANIZATION_TYPE_Industry: type 11       31232 non-null  uint8
 172  ORGANIZATION_TYPE_Industry: type 12       31232 non-null  uint8
 173  ORGANIZATION_TYPE_Industry: type 13       31232 non-null  uint8
 174  ORGANIZATION_TYPE_Industry: type 2        31232 non-null  uint8
 175  ORGANIZATION_TYPE_Industry: type 3        31232 non-null  uint8
 176  ORGANIZATION_TYPE_Industry: type 4        31232 non-null  uint8
 177  ORGANIZATION_TYPE_Industry: type 5        31232 non-null  uint8
 178  ORGANIZATION_TYPE_Industry: type 6        31232 non-null  uint8
 179  ORGANIZATION_TYPE_Industry: type 7        31232 non-null  uint8
 180  ORGANIZATION_TYPE_Industry: type 8        31232 non-null  uint8
 181  ORGANIZATION_TYPE_Industry: type 9        31232 non-null  uint8
 182  ORGANIZATION_TYPE_Insurance               31232 non-null  uint8
 183  ORGANIZATION_TYPE_Kindergarten            31232 non-null  uint8
 184  ORGANIZATION_TYPE_Legal Services          31232 non-null  uint8
 185  ORGANIZATION_TYPE_Medicine                31232 non-null  uint8
 186  ORGANIZATION_TYPE_Military                31232 non-null  uint8
 187  ORGANIZATION_TYPE_Mobile                  31232 non-null  uint8
 188  ORGANIZATION_TYPE_Other                   31232 non-null  uint8
 189  ORGANIZATION_TYPE_Police                  31232 non-null  uint8
 190  ORGANIZATION_TYPE_Postal                  31232 non-null  uint8
 191  ORGANIZATION_TYPE_Realtor                 31232 non-null  uint8
 192  ORGANIZATION_TYPE_Religion                31232 non-null  uint8
 193  ORGANIZATION_TYPE_Restaurant              31232 non-null  uint8
 194  ORGANIZATION_TYPE_School                  31232 non-null  uint8
 195  ORGANIZATION_TYPE_Security                31232 non-null  uint8
 196  ORGANIZATION_TYPE_Security Ministries     31232 non-null  uint8
 197  ORGANIZATION_TYPE_Self-employed           31232 non-null  uint8
 198  ORGANIZATION_TYPE_Services                31232 non-null  uint8
 199  ORGANIZATION_TYPE_Telecom                 31232 non-null  uint8
 200  ORGANIZATION_TYPE_Trade: type 1           31232 non-null  uint8
 201  ORGANIZATION_TYPE_Trade: type 2           31232 non-null  uint8
 202  ORGANIZATION_TYPE_Trade: type 3           31232 non-null  uint8
 203  ORGANIZATION_TYPE_Trade: type 4           31232 non-null  uint8
 204  ORGANIZATION_TYPE_Trade: type 5           31232 non-null  uint8
 205  ORGANIZATION_TYPE_Trade: type 6           31232 non-null  uint8
 206  ORGANIZATION_TYPE_Trade: type 7           31232 non-null  uint8
 207  ORGANIZATION_TYPE_Transport: type 1       31232 non-null  uint8
 208  ORGANIZATION_TYPE_Transport: type 2       31232 non-null  uint8
 209  ORGANIZATION_TYPE_Transport: type 3       31232 non-null  uint8
 210  ORGANIZATION_TYPE_Transport: type 4       31232 non-null  uint8
 211  ORGANIZATION_TYPE_University              31232 non-null  uint8
 212  ORGANIZATION_TYPE_XNA                     31232 non-null  uint8
 213  FONDKAPREMONT_MODE_org spec account       31232 non-null  uint8
 214  FONDKAPREMONT_MODE_reg oper account       31232 non-null  uint8
 215  FONDKAPREMONT_MODE_reg oper spec account  31232 non-null  uint8
 216  HOUSETYPE_MODE_specific housing           31232 non-null  uint8
 217  HOUSETYPE_MODE_terraced house             31232 non-null  uint8
 218  WALLSMATERIAL_MODE_Mixed                  31232 non-null  uint8
 219  WALLSMATERIAL_MODE_Monolithic             31232 non-null  uint8
 220  WALLSMATERIAL_MODE_Others                 31232 non-null  uint8
 221  WALLSMATERIAL_MODE_Panel                  31232 non-null  uint8
 222  WALLSMATERIAL_MODE_Stone, brick           31232 non-null  uint8
 223  WALLSMATERIAL_MODE_Wooden                 31232 non-null  uint8
dtypes: float64(66), int64(46), uint8(112)
memory usage: 30.3 MB

In [73]:
var_columns = [col for col in temp_df.columns if col != 'TARGET']
x, y = temp_df[var_columns].copy(), temp_df.TARGET.copy()
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.3, random_state=42)
ytrain.value_counts(), ytrain.value_counts(normalize=True)*100

(0    20433
 1     1429
 Name: TARGET, dtype: int64,
 0    93.463544
 1     6.536456
 Name: TARGET, dtype: float64)

In [74]:
scaler = get_minmax_scaler(xtrain, xtrain.columns)
xtrain = apply_transform(scaler, xtrain)
xtest = apply_transform(scaler, xtest)

In [75]:
# xtrain.info(verbose=True, show_counts=True)

In [76]:
xtrain_balance, ytrain_balance = xtrain.copy(), ytrain.copy()
xtrain_balance, ytrain_balance = over_sampling.SMOTE().fit_resample(xtrain_balance, ytrain_balance)
ytrain_balance.value_counts()

0    20433
1    20433
Name: TARGET, dtype: int64

# **Modeling**

In [77]:
def eval_classification(model, xtrain, ytrain, xtest, ytest, threshold=0.5):
    ypred_proba_test = model.predict_proba(xtest)
    ypred_proba_train = model.predict_proba(xtrain)
    ypred_datatest = np.where(ypred_proba_test[:,1]>=threshold, 1, 0 )
    ypred_datatrain = np.where(ypred_proba_train[:,1]>=threshold, 1, 0 )
    cm = confusion_matrix(ytest, ypred_datatest)
    tn, fp, fn, tp = cm.ravel()
    print("Accuracy (Test Set): %.2f" % accuracy_score(ytest, ypred_datatest))
    print("Precision (Test Set): %.2f" % precision_score(ytest, ypred_datatest))
    # print("Precision (Train Set): %.2f" % precision_score(ytrain, ypred_datatrain))
    print("Recall (Test Set): %.2f" % recall_score(ytest, ypred_datatest))
    # print("Recall (Train Set): %.2f" % recall_score(ytrain, ypred_datatrain))
    print("F1-Score (Test Set): %.2f" % f1_score(ytest, ypred_datatest))
    # print("F1-Score (Train Set): %.2f" % f1_score(ytrain, ypred))
    print("AUC (test-proba): %.2f" % roc_auc_score(ytest, ypred_proba_test[:,1] ))
    print("AUC (train-proba): %.2f" % roc_auc_score(ytrain, ypred_proba_train[:,1] ))
    print('tp : {}\nfp  : {}\nfn  : {}\ntn  : {}\n'.format(tp, fp, fn, tn))

## **RandomForest**

In [78]:
rf = RandomForestClassifier(random_state=42)
temp_rf = rf.fit(xtrain, ytrain.values.ravel())
eval_classification(rf, xtrain, ytrain, xtest, ytest)

Accuracy (Test Set): 0.94
Precision (Test Set): 0.67
Recall (Test Set): 0.00
F1-Score (Test Set): 0.01
AUC (test-proba): 0.69
AUC (train-proba): 1.00
tp : 2
fp  : 1
fn  : 589
tn  : 8778

In [79]:
temp_rf = rf.fit(xtrain_balance, ytrain_balance.values.ravel())
eval_classification(rf, xtrain_balance, ytrain_balance, xtest, ytest)

Accuracy (Test Set): 0.94
Precision (Test Set): 0.24
Recall (Test Set): 0.01
F1-Score (Test Set): 0.02
AUC (test-proba): 0.68
AUC (train-proba): 1.00
tp : 7
fp  : 22
fn  : 584
tn  : 8757

## **XGBoost**

In [80]:
xgb = XGBClassifier(random_state=42)
temp_xgb = xgb.fit(xtrain, ytrain.values.ravel())
eval_classification(xgb, xtrain, ytrain, xtest, ytest)

Accuracy (Test Set): 0.93
Precision (Test Set): 0.32
Recall (Test Set): 0.04
F1-Score (Test Set): 0.07
AUC (test-proba): 0.72
AUC (train-proba): 1.00
tp : 23
fp  : 48
fn  : 568
tn  : 8731

## **Logistic Regression**

In [81]:
lr = LogisticRegression()
temp_lr = lr.fit(xtrain, ytrain.values.ravel())
eval_classification(temp_lr, xtrain, ytrain, xtest, ytest)

Accuracy (Test Set): 0.94
Precision (Test Set): 0.25
Recall (Test Set): 0.01
F1-Score (Test Set): 0.01
AUC (test-proba): 0.75
AUC (train-proba): 0.78
tp : 4
fp  : 12
fn  : 587
tn  : 8767

C:\SYS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [82]:
temp_lr = lr.fit(xtrain_balance, ytrain_balance.values.ravel())
eval_classification(temp_lr, xtrain_balance, ytrain_balance, xtest, ytest)

Accuracy (Test Set): 0.71
Precision (Test Set): 0.13
Recall (Test Set): 0.61
F1-Score (Test Set): 0.21
AUC (test-proba): 0.73
AUC (train-proba): 0.82
tp : 362
fp  : 2496
fn  : 229
tn  : 6283

C:\SYS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(